=== VishwaPriyan-S/WebTechnology/src/main/webapp/feedbacks.dtd
<!ELEMENT feedbacks (feedback*)>
<!ELEMENT feedback (name, rating, comments)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT comments (#PCDATA)>

=== VishwaPriyan-S/WebTechnology/src/main/webapp/feedback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE feedbacks SYSTEM "feedbacks.dtd">
<?xml-stylesheet type="text/xsl" href="feedbacks.xsl"?>
<feedbacks>
    <feedback>
        <name>Vishwa</name>
        <rating>5</rating>
        <comments>Loved the chocolate ice cream!</comments>
    </feedback>
    <feedback>
        <name>Priya</name>
        <rating>3</rating>
        <comments>Vanilla was okay, could be better.</comments>
    </feedback>
    <feedback>
        <name>Arun</name>
        <rating>4</rating>
        <comments>Great service and tasty ice cream!</comments>
    </feedback>
</feedbacks>
